M48
; DRILL file {KiCad 7.0.7} date 2023 December 31, Sunday 12:38:16
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-31T12:38:16+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0236
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C0.0551
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T4C0.0717
%
G90
G05
T1
X7.7087Y-5.2126
X7.7087Y-5.378
T2
X7.7146Y-5.2697
X7.7146Y-5.3189
T3
X7.8661Y-5.2244
X8.063Y-5.2244
T4
X7.8661Y-5.2953
X8.063Y-5.2953
T0
M30
